# Workflow to build and publish app on Play Store
# Test 1
name: Deploy App CI

on:
  push:
#    paths:
#      - 'OrbitLearn/**'
# TEST 2!
    branches: [ main, develop, test-build ]

jobs:
#----------------------------------------------------#
  buildForAndroidPlatform:
    name: Build For Android Platform
    runs-on: ubuntu-latest
    steps:
    
      - name: Checkout With Tags
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          
      - name: Cache Library
        uses: actions/cache@v2
        with:
          path: OrbitLearn/Library
          key: OrbitLearn/Library
          
      - name: Unity Build
        uses: game-ci/unity-builder@v2
        id: unityBuildStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          projectPath: ./OrbitLearn
          targetPlatform: Android
          androidAppBundle: true
          androidKeystoreName: orbitlearn.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
          
      - name: Unity Build Number
        run: echo 'Project Version:${{ steps.unityBuildStep.outputs.buildVersion }}'
      
      - name: Artifact Upload
        uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build/Android
#----------------------------------------------------#
  releaseToGooglePlay:
    name: Release to the Google Play Store
    runs-on: ubuntu-latest
    needs: buildForAndroidPlatform
    env:
      GOOGLE_PLAY_KEY_FILE: ${{ secrets.GOOGLE_PLAY_KEY_FILE }}
      GOOGLE_PLAY_KEY_FILE_PATH: ${{ format('{0}/fastlane/google-fastlane.json', github.workspace) }}
      ANDROID_BUILD_FILE_PATH: ${{ format('{0}/build/Android/Android.aab', github.workspace) }}
      ANDROID_PACKAGE_NAME: ${{ secrets.ANDROID_PACKAGE_NAME }}
    steps:
    
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Download Android Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-Android
          path: build/Android
          
      - name: Add Authentication
        run: echo "$GOOGLE_PLAY_KEY_FILE" > $GOOGLE_PLAY_KEY_FILE_PATH
        
      - name: Install Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.2
          bundler-cache: true
          
      - name: Upload to Google Play Internal
        uses: maierj/fastlane-action@v2.0.1
        with:
          lane: 'android internal'
          
      - name: Cleanup to avoid storage limit
        if: always()
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-Android
